### PR TITLE
Changed menu

### PR DESCRIPTION
**Pull request by nchernia**
Changed select menu to include all the maps in public Juicebox. Using the Javascript library chosen. 
Install via npm install chosen-js

### CODE REVIEW

**Comment by sa501428** [comment]
for issue #35

**Comment by jrobinso** [comment]
Hi,  this file (hic.html) can't have any node dependencies,  it is the public html file.     Please include either an external reference to the needed jss and css files, or create a new folder ("vendor") and copy the files to there.   Thanks.

**Comment by sa501428** [comment]
@nchernia if you're using chosen-js just for the search bar dropdown, another alternative may be to use the jquery version: http://jsfiddle.net/sschauhan/7qwaw0v1/

**Comment by jrobinso** [comment]
Shouldn't it also work to just copy the css & js to a folder we can serve it from?    If we go this route I'm suggesting we copy it in the repo to a new folder called "vendor".  The grunt build could copy it to "dist".      So in  "dev/hic-dev.html" reference vendor/whatever.js,  vendor/whatever.css.   In hic.html we would reference dist/whatever.js.    In the project structure we use dev/hic-dev.html for development and testing,   hic.html is deployed and needs to work stand-alone with no development dependencies (such as node or node-modules, etc).

**Comment by jrobinso** [comment]
This of course assumes the license for this module allows that,  I haven't looked at it.

**Comment by nchernia** [comment]
I think I fixed this? I'm a little confused using forks.

**Comment by jrobinso** [comment]
Looks fixed to me.

**Pull request merged**
