### PR TITLE
css no contains sym-link to sass/hic.css

### PR DESCRIPTION
**Pull request by sa501428**

### CODE REVIEW

**Comment by jrobinso** [comment]
@turner @sa501428 Could one of you comment on this? What is the issue (if any) and is it resolved?

**Comment by sa501428** [comment]
Pulled in updates from @turner into the branch I'm working on.

**Comment by jrobinso** [comment]
OK, so all is good?

**Comment by turner** [comment]
@sa501428 what is your current status? There is nothing you need to do to use our sass generated css. 

The change I made was to create a symlink to sass/hic.css from the css directory:

screen shot 2017-03-15 at 9 09 45 pm

**Comment by sa501428** [comment]
The dist folder is missing; is this something I build?
For now I've copied it from the main site.

**Comment by turner** [comment]
Yes. Run `grunt` from command line within the project.

**Comment by turner** [comment]
That builds `hic.css` and `hic.js` within `dist/`

**Comment by sa501428** [comment]
Ah, I see. Thanks!

**Pull request merged**
